const { saveProfilePhoto } = require("../utils/address");
const { isValidPhilippineMobile, isValidEmail, normalizeEmail, validateTechnicianPayload } = require("../utils/validation");

module.exports = function registerTechnicianRoutes(app, { getPool, sql, requireUser, requireAdmin, logAction, actorName, sendInternalError, hashPassword }) {
  app.get("/api/technicians", requireUser, async (req, res) => {
    if (req.user.role !== "admin") return res.status(403).json({ message: "Admin access required." });
    try { const result = await (await getPool()).request().query(`SELECT Id AS id, Name AS name, Specialty AS specialty, Status AS status, PhoneNumber AS phoneNumber, Email AS email, Address AS address, ProfilePhoto AS profilePhoto FROM Technicians ORDER BY Id DESC`); res.json(result.recordset); } catch (error) { sendInternalError(res, error, "Request failed"); }
  });

  app.post("/api/technicians", requireUser, requireAdmin, async (req, res) => {
    const { name, specialty, status = "Active", phoneNumber, address, latitude, longitude, profilePhoto } = req.body;
    const email = normalizeEmail(req.body.email);
    const validationError = validateTechnicianPayload({ name, specialty, phoneNumber, email, address });
    if (validationError) return res.status(400).json({ message: validationError });
    try {
      const pool = await getPool();
      const existingUser = await pool.request().input("Email", sql.NVarChar(150), email).query("SELECT TOP 1 Id FROM Users WHERE Email = @Email");
      if (existingUser.recordset.length) return res.status(409).json({ message: "That email is already registered." });
      const savedPhoto = await saveProfilePhoto(profilePhoto);
      const result = await pool.request().input("Name", sql.NVarChar(100), name).input("Specialty", sql.NVarChar(100), specialty).input("Status", sql.NVarChar(50), status).input("PhoneNumber", sql.NVarChar(11), phoneNumber.trim()).input("Email", sql.NVarChar(255), email).input("Address", sql.NVarChar(255), address.trim()).input("Latitude", sql.Decimal(9, 6), latitude === undefined ? null : Number(latitude)).input("Longitude", sql.Decimal(9, 6), longitude === undefined ? null : Number(longitude)).input("ProfilePhoto", sql.NVarChar(255), savedPhoto || null).query(`INSERT INTO Technicians (Name, Specialty, Status, PhoneNumber, Email, Address, Latitude, Longitude, ProfilePhoto) OUTPUT INSERTED.Id AS id, INSERTED.Name AS name, INSERTED.Specialty AS specialty, INSERTED.Status AS status, INSERTED.PhoneNumber AS phoneNumber, INSERTED.Email AS email, INSERTED.Address AS address, INSERTED.ProfilePhoto AS profilePhoto VALUES (@Name, @Specialty, @Status, @PhoneNumber, @Email, @Address, @Latitude, @Longitude, @ProfilePhoto)`);
      const initialPassword = phoneNumber.trim();
      const { salt, hash } = hashPassword(initialPassword);
      await pool.request().input("Username", sql.NVarChar(80), email.split("@")[0].toLowerCase()).input("FullName", sql.NVarChar(100), name).input("Email", sql.NVarChar(150), email).input("PasswordHash", sql.NVarChar(255), hash).input("PasswordSalt", sql.NVarChar(80), salt).input("Role", sql.NVarChar(30), "technician").input("MustChangePassword", sql.Bit, 1).query("INSERT INTO Users (Username, FullName, Email, PasswordHash, PasswordSalt, Role, MustChangePassword) VALUES (@Username, @FullName, @Email, @PasswordHash, @PasswordSalt, @Role, @MustChangePassword)");
      await logAction(`Created technician ${name}`, actorName(req), "Technicians", result.recordset[0].id);
      res.status(201).json(result.recordset[0]);
    } catch (error) { sendInternalError(res, error, "Request failed"); }
  });

  app.put("/api/technicians/:id", requireUser, requireAdmin, async (req, res) => {
    const { name, specialty, status = "Active", phoneNumber, address, latitude, longitude, profilePhoto } = req.body;
    const email = normalizeEmail(req.body.email);
    const validationError = validateTechnicianPayload({ name, specialty, phoneNumber, email, address });
    if (validationError) return res.status(400).json({ message: validationError });
    try {
      const pool = await getPool();
      const duplicate = await pool.request().input("Email", sql.NVarChar(255), email).input("Id", sql.Int, Number(req.params.id)).query("SELECT TOP 1 Id FROM Technicians WHERE Email = @Email AND Id <> @Id");
      if (duplicate.recordset.length) return res.status(409).json({ message: "That email is already assigned to another technician." });
      const existing = await pool.request().input("Id", sql.Int, Number(req.params.id)).query("SELECT ProfilePhoto, Email FROM Technicians WHERE Id = @Id");
      if (!existing.recordset.length) return res.status(404).json({ message: "Technician not found." });
      const emailInUse = await pool.request().input("Email", sql.NVarChar(150), email).input("OldEmail", sql.NVarChar(255), existing.recordset[0].Email).query("SELECT TOP 1 Id FROM Users WHERE Email = @Email AND Email <> @OldEmail");
      if (emailInUse.recordset.length) return res.status(409).json({ message: "That email is already registered." });
      const savedPhoto = profilePhoto ? await saveProfilePhoto(profilePhoto) : existing.recordset[0].ProfilePhoto;
      const result = await pool.request().input("Id", sql.Int, Number(req.params.id)).input("Name", sql.NVarChar(100), name).input("Specialty", sql.NVarChar(100), specialty).input("Status", sql.NVarChar(50), status).input("PhoneNumber", sql.NVarChar(11), phoneNumber.trim()).input("Email", sql.NVarChar(255), email).input("Address", sql.NVarChar(255), address.trim()).input("ProfilePhoto", sql.NVarChar(255), savedPhoto || null).query(`UPDATE Technicians SET Name = @Name, Specialty = @Specialty, Status = @Status, PhoneNumber = @PhoneNumber, Email = @Email, Address = @Address, ProfilePhoto = @ProfilePhoto OUTPUT INSERTED.Id AS id, INSERTED.Name AS name, INSERTED.Specialty AS specialty, INSERTED.Status AS status, INSERTED.PhoneNumber AS phoneNumber, INSERTED.Email AS email, INSERTED.Address AS address, INSERTED.ProfilePhoto AS profilePhoto WHERE Id = @Id`);
      await pool.request().input("OldEmail", sql.NVarChar(255), existing.recordset[0].Email).input("FullName", sql.NVarChar(100), name.trim()).input("Email", sql.NVarChar(150), email).query("UPDATE Users SET FullName = @FullName, Email = @Email WHERE Role = 'technician' AND Email = @OldEmail");
      await logAction(`Updated technician ${name}`, actorName(req), "Technicians", req.params.id);
      res.json(result.recordset[0]);
    } catch (error) { sendInternalError(res, error, "Request failed"); }
  });

  app.get("/api/technicians/me", requireUser, async (req, res) => { if (req.user.role !== "technician") return res.status(403).json({ message: "Technician access required." }); try { const result = await (await getPool()).request().input("UserId", sql.Int, req.user.id).query("SELECT t.Id AS id, t.Name AS name, t.Specialty AS specialty, t.Status AS status, t.PhoneNumber AS phoneNumber, t.Email AS email, t.Address AS address, t.ProfilePhoto AS profilePhoto FROM Technicians t INNER JOIN Users u ON u.Email = t.Email WHERE u.Id = @UserId AND u.Role = 'technician'"); if (!result.recordset.length) return res.status(404).json({ message: "No technician profile is linked to this account." }); res.json(result.recordset[0]); } catch (error) { sendInternalError(res, error, "Request failed"); } });
  app.put("/api/technicians/me", requireUser, async (req, res) => { if (req.user.role !== "technician") return res.status(403).json({ message: "Technician access required." }); const { name, phoneNumber, address, profilePhoto } = req.body; const email = normalizeEmail(req.body.email); if (!String(name || "").trim() || !isValidPhilippineMobile(phoneNumber) || !isValidEmail(email) || !String(address || "").trim()) return res.status(400).json({ message: "Provide a name, valid Philippine mobile number, valid email, and address." }); try { const pool = await getPool(); const current = await pool.request().input("UserId", sql.Int, req.user.id).query("SELECT t.Id, t.ProfilePhoto, t.Email FROM Technicians t INNER JOIN Users u ON u.Email = t.Email WHERE u.Id = @UserId AND u.Role = 'technician'"); if (!current.recordset.length) return res.status(404).json({ message: "No technician profile is linked to this account." }); const technician = current.recordset[0]; const duplicate = await pool.request().input("Email", sql.NVarChar(255), email).input("Id", sql.Int, technician.Id).query("SELECT TOP 1 Id FROM Technicians WHERE Email = @Email AND Id <> @Id"); if (duplicate.recordset.length) return res.status(409).json({ message: "That email is already assigned to another technician." }); const emailInUse = await pool.request().input("Email", sql.NVarChar(150), email).input("UserId", sql.Int, req.user.id).query("SELECT TOP 1 Id FROM Users WHERE Email = @Email AND Id <> @UserId"); if (emailInUse.recordset.length) return res.status(409).json({ message: "That email is already registered." }); const savedPhoto = profilePhoto ? await saveProfilePhoto(profilePhoto) : technician.ProfilePhoto; const result = await pool.request().input("Id", sql.Int, technician.Id).input("Name", sql.NVarChar(100), name.trim()).input("PhoneNumber", sql.NVarChar(11), phoneNumber.trim()).input("Email", sql.NVarChar(255), email).input("Address", sql.NVarChar(255), address.trim()).input("ProfilePhoto", sql.NVarChar(255), savedPhoto || null).query("UPDATE Technicians SET Name = @Name, PhoneNumber = @PhoneNumber, Email = @Email, Address = @Address, ProfilePhoto = @ProfilePhoto OUTPUT INSERTED.Id AS id, INSERTED.Name AS name, INSERTED.Specialty AS specialty, INSERTED.Status AS status, INSERTED.PhoneNumber AS phoneNumber, INSERTED.Email AS email, INSERTED.Address AS address, INSERTED.ProfilePhoto AS profilePhoto WHERE Id = @Id"); await pool.request().input("UserId", sql.Int, req.user.id).input("Name", sql.NVarChar(100), name.trim()).input("Email", sql.NVarChar(150), email).query("UPDATE Users SET FullName = @Name, Email = @Email WHERE Id = @UserId"); await logAction(`Updated technician profile ${name}`, actorName(req), "Technicians", technician.Id); res.json(result.recordset[0]); } catch (error) { if (error.message.includes("UNIQUE")) return res.status(409).json({ message: "That email is already registered." }); sendInternalError(res, error, "Technician profile update failed"); } });
  app.delete("/api/technicians/:id", requireUser, requireAdmin, async (req, res) => { try { const pool = await getPool(); const technician = await pool.request().input("Id", sql.Int, Number(req.params.id)).query("SELECT Email FROM Technicians WHERE Id = @Id"); if (!technician.recordset.length) return res.status(404).json({ message: "Technician not found." }); await pool.request().input("Id", sql.Int, Number(req.params.id)).query("DELETE FROM Schedules WHERE TechnicianId = @Id; DELETE FROM Technicians WHERE Id = @Id; IF NOT EXISTS (SELECT 1 FROM Technicians) DBCC CHECKIDENT ('Technicians', RESEED, 0)"); if (technician.recordset[0].Email) await pool.request().input("Email", sql.NVarChar(255), technician.recordset[0].Email).query("DELETE FROM Users WHERE Role = 'technician' AND Email = @Email"); await logAction("Deleted a technician", actorName(req), "Technicians", req.params.id); res.status(204).end(); } catch (error) { sendInternalError(res, error, "Request failed"); } });
};
